/**
 * @fileoverview AI Treatment Planning Service
 *
 * Uses AI to generate optimal treatment plans based on patient data,
 * clinical findings, and historical outcomes. This is what makes the
 * platform INDISPENSABLE - intelligent decision support.
 *
 * @module domain/treatment-journey/services/AITreatmentPlanningService
 */

// Treatment journey types are available for future integration
// import type { TreatmentJourney } from '../entities/TreatmentJourney.js';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Clinical assessment input for treatment planning
 */
export interface ClinicalAssessmentInput {
  // Patient demographics
  readonly patientAge: number;
  readonly patientGender: 'MALE' | 'FEMALE' | 'OTHER';

  // Dental status
  readonly missingTeeth: readonly number[]; // FDI notation
  readonly decayedTeeth: readonly number[];
  readonly periodontalStatus: 'HEALTHY' | 'GINGIVITIS' | 'MILD_PERIO' | 'MODERATE_PERIO' | 'SEVERE_PERIO';
  readonly existingRestorations: readonly {
    readonly tooth: number;
    readonly type: string;
    readonly condition: 'GOOD' | 'FAIR' | 'FAILING';
  }[];

  // Bone assessment (if available)
  readonly boneQuality?: 'D1' | 'D2' | 'D3' | 'D4';
  readonly boneHeight?: Record<number, number>; // tooth number -> mm
  readonly boneWidth?: Record<number, number>;
  readonly sinusProximity?: boolean;
  readonly nerveProximity?: boolean;

  // Medical history
  readonly medicalConditions: readonly string[];
  readonly medications: readonly string[];
  readonly allergies: readonly string[];
  readonly smokingStatus: 'NEVER' | 'FORMER' | 'CURRENT';
  readonly diabetesStatus?: 'NONE' | 'CONTROLLED' | 'UNCONTROLLED';

  // Patient preferences
  readonly budgetRange?: { min: number; max: number; currency: string };
  readonly timeConstraints?: { maxMonths: number };
  readonly aestheticPriority: 'LOW' | 'MEDIUM' | 'HIGH';
  readonly functionalPriority: 'LOW' | 'MEDIUM' | 'HIGH';
}

/**
 * Treatment option generated by AI
 */
export interface TreatmentOption {
  readonly id: string;
  readonly name: string;
  readonly description: string;

  // Classification
  readonly category:
    | 'CONSERVATIVE'
    | 'PROSTHETIC'
    | 'IMPLANT'
    | 'ALL_ON_X'
    | 'FULL_MOUTH_REHAB'
    | 'COMBINATION';
  readonly complexity: 'SIMPLE' | 'MODERATE' | 'COMPLEX' | 'HIGHLY_COMPLEX';

  // Treatment components
  readonly phases: readonly TreatmentPhase[];
  readonly totalProcedures: number;

  // Outcomes
  readonly predictedSuccessRate: number; // 0-100%
  readonly longevityYears: number; // Expected lifespan
  readonly functionalScore: number; // 1-10
  readonly aestheticScore: number; // 1-10

  // Cost & time
  readonly estimatedCost: {
    readonly min: number;
    readonly max: number;
    readonly currency: string;
  };
  readonly estimatedDurationMonths: number;
  readonly appointmentsRequired: number;

  // Risk assessment
  readonly risks: readonly TreatmentRisk[];
  readonly contraindications: readonly string[];

  // AI confidence
  readonly aiConfidence: number; // 0-100%
  readonly reasoning: string;
}

/**
 * Phase within a treatment option
 */
export interface TreatmentPhase {
  readonly name: string;
  readonly description: string;
  readonly procedures: readonly ProcedureRecommendation[];
  readonly durationWeeks: number;
  readonly requiresHealing: boolean;
  readonly healingWeeks?: number;
}

/**
 * Individual procedure recommendation
 */
export interface ProcedureRecommendation {
  readonly code: string; // Dental procedure code
  readonly name: string;
  readonly description: string;
  readonly teethInvolved: readonly number[];
  readonly estimatedCost: number;
  readonly durationMinutes: number;
  readonly anesthesiaRequired: boolean;
  readonly specialistRequired?: string;
}

/**
 * Treatment risk
 */
export interface TreatmentRisk {
  readonly type: string;
  readonly severity: 'LOW' | 'MEDIUM' | 'HIGH';
  readonly probability: number; // 0-100%
  readonly mitigation: string;
}

/**
 * AI-generated treatment plan
 */
export interface AITreatmentPlan {
  readonly id: string;
  readonly generatedAt: Date;
  readonly patientId: string;
  readonly assessmentSummary: string;

  // Options (ranked by AI recommendation)
  readonly recommendedOption: TreatmentOption;
  readonly alternativeOptions: readonly TreatmentOption[];

  // Comparison matrix
  readonly comparisonMatrix: {
    readonly criteria: readonly string[];
    readonly scores: Record<string, Record<string, number>>; // optionId -> criterion -> score
  };

  // AI insights
  readonly clinicalInsights: readonly string[];
  readonly patientConsiderations: readonly string[];
  readonly urgencyLevel: 'ROUTINE' | 'SOON' | 'URGENT' | 'EMERGENCY';
  readonly urgencyReasoning: string;

  // For patient communication
  readonly patientFriendlySummary: string;
  readonly visualizationData?: TreatmentVisualization;
}

/**
 * Data for treatment visualization
 */
export interface TreatmentVisualization {
  readonly beforeState: ToothState[];
  readonly afterState: ToothState[];
  readonly highlightedTeeth: number[];
  readonly annotations: readonly {
    readonly tooth: number;
    readonly label: string;
    readonly type: 'EXTRACTION' | 'IMPLANT' | 'CROWN' | 'BRIDGE' | 'FILLING' | 'ROOT_CANAL';
  }[];
}

export interface ToothState {
  readonly toothNumber: number;
  readonly status: 'PRESENT' | 'MISSING' | 'EXTRACTED' | 'IMPLANT';
  readonly restoration?: string;
  readonly condition: 'HEALTHY' | 'DECAYED' | 'RESTORED' | 'FAILING';
}

// ============================================================================
// AI TREATMENT PLANNING SERVICE
// ============================================================================

/**
 * Generates AI-powered treatment plan based on clinical assessment
 *
 * This function builds the prompt and context for GPT-4o to analyze.
 * In production, this would call the OpenAI API.
 */
export function generateTreatmentPlanPrompt(assessment: ClinicalAssessmentInput): string {
  const prompt = `You are an expert dental treatment planning AI assistant. Analyze the following patient case and generate optimal treatment recommendations.

## Patient Profile
- Age: ${assessment.patientAge} years old
- Gender: ${assessment.patientGender}
- Smoking: ${assessment.smokingStatus}
${assessment.diabetesStatus ? `- Diabetes: ${assessment.diabetesStatus}` : ''}

## Dental Status
- Missing teeth (FDI): ${assessment.missingTeeth.join(', ') || 'None'}
- Decayed teeth: ${assessment.decayedTeeth.join(', ') || 'None'}
- Periodontal status: ${assessment.periodontalStatus}
- Existing restorations: ${assessment.existingRestorations.length} restorations

## Medical History
- Conditions: ${assessment.medicalConditions.join(', ') || 'None reported'}
- Medications: ${assessment.medications.join(', ') || 'None'}
- Allergies: ${assessment.allergies.join(', ') || 'None known'}

## Bone Assessment
${assessment.boneQuality ? `- Bone quality: ${assessment.boneQuality}` : '- Bone quality: Not assessed'}
${assessment.sinusProximity ? '- Sinus proximity concerns noted' : ''}
${assessment.nerveProximity ? '- Nerve proximity concerns noted' : ''}

## Patient Preferences
${assessment.budgetRange ? `- Budget range: ${assessment.budgetRange.min}-${assessment.budgetRange.max} ${assessment.budgetRange.currency}` : '- Budget: Not specified'}
${assessment.timeConstraints ? `- Time constraint: Complete within ${assessment.timeConstraints.maxMonths} months` : '- Time: Flexible'}
- Aesthetic priority: ${assessment.aestheticPriority}
- Functional priority: ${assessment.functionalPriority}

## Instructions
Generate 3-4 treatment options ranging from conservative to comprehensive. For each option, provide:
1. Clear treatment name and description
2. Step-by-step phases with procedures
3. Predicted success rate based on clinical evidence
4. Cost estimate range
5. Duration and number of appointments
6. Associated risks and mitigations
7. Why this option might be best for this patient

Rank options by your recommendation, considering patient preferences and clinical factors.`;

  return prompt;
}

/**
 * Analyzes missing teeth pattern to determine optimal restoration strategy
 */
export function analyzeRestorationStrategy(
  missingTeeth: readonly number[],
  boneQuality?: 'D1' | 'D2' | 'D3' | 'D4'
): {
  strategy: 'SINGLE_IMPLANTS' | 'IMPLANT_BRIDGE' | 'ALL_ON_4' | 'ALL_ON_6' | 'REMOVABLE' | 'HYBRID';
  reasoning: string;
} {
  const count = missingTeeth.length;

  // Check for edentulous arch
  const maxillaryTeeth = missingTeeth.filter((t) => t >= 11 && t <= 28);
  const mandibularTeeth = missingTeeth.filter((t) => t >= 31 && t <= 48);

  const maxillaryEdentulous = maxillaryTeeth.length >= 14;
  const mandibularEdentulous = mandibularTeeth.length >= 14;

  if (maxillaryEdentulous || mandibularEdentulous) {
    if (boneQuality === 'D4' || boneQuality === 'D3') {
      return {
        strategy: 'ALL_ON_6',
        reasoning: 'Full arch missing with compromised bone quality - All-on-6 provides better load distribution',
      };
    }
    return {
      strategy: 'ALL_ON_4',
      reasoning: 'Full arch missing with adequate bone - All-on-4 is cost-effective and proven',
    };
  }

  if (count === 0) {
    return {
      strategy: 'SINGLE_IMPLANTS',
      reasoning: 'No missing teeth - focus on preserving existing dentition',
    };
  }

  if (count <= 2) {
    return {
      strategy: 'SINGLE_IMPLANTS',
      reasoning: 'Few missing teeth - individual implants provide optimal independent function',
    };
  }

  if (count <= 4 && areTeethAdjacent(missingTeeth)) {
    return {
      strategy: 'IMPLANT_BRIDGE',
      reasoning: 'Adjacent missing teeth - implant-supported bridge reduces cost and appointments',
    };
  }

  if (count <= 6) {
    return {
      strategy: 'IMPLANT_BRIDGE',
      reasoning: 'Multiple missing teeth in segments - strategic implant placement with bridges',
    };
  }

  return {
    strategy: 'HYBRID',
    reasoning: 'Complex case with multiple missing teeth - combination approach recommended',
  };
}

function areTeethAdjacent(teeth: readonly number[]): boolean {
  if (teeth.length <= 1) return true;

  const sorted = [...teeth].sort((a, b) => a - b);
  for (let i = 1; i < sorted.length; i++) {
    const current = sorted[i];
    const previous = sorted[i - 1];
    if (current === undefined || previous === undefined) continue;
    const diff = current - previous;
    // Adjacent teeth have diff of 1 (same quadrant) or are in same region
    if (diff > 2) return false;
  }
  return true;
}

/**
 * Calculates predicted treatment success rate based on clinical factors
 */
export function calculatePredictedSuccessRate(
  assessment: ClinicalAssessmentInput,
  treatmentType: TreatmentOption['category']
): { rate: number; factors: readonly { factor: string; impact: number }[] } {
  let baseRate = 95; // Base success rate for modern dental treatments
  const factors: { factor: string; impact: number }[] = [];

  // Age factor
  if (assessment.patientAge > 70) {
    baseRate -= 3;
    factors.push({ factor: 'Age over 70', impact: -3 });
  }

  // Smoking impact
  if (assessment.smokingStatus === 'CURRENT') {
    baseRate -= 10;
    factors.push({ factor: 'Current smoker', impact: -10 });
  } else if (assessment.smokingStatus === 'FORMER') {
    baseRate -= 3;
    factors.push({ factor: 'Former smoker', impact: -3 });
  }

  // Diabetes impact
  if (assessment.diabetesStatus === 'UNCONTROLLED') {
    baseRate -= 15;
    factors.push({ factor: 'Uncontrolled diabetes', impact: -15 });
  } else if (assessment.diabetesStatus === 'CONTROLLED') {
    baseRate -= 5;
    factors.push({ factor: 'Controlled diabetes', impact: -5 });
  }

  // Periodontal status impact
  switch (assessment.periodontalStatus) {
    case 'SEVERE_PERIO':
      baseRate -= 12;
      factors.push({ factor: 'Severe periodontal disease', impact: -12 });
      break;
    case 'MODERATE_PERIO':
      baseRate -= 7;
      factors.push({ factor: 'Moderate periodontal disease', impact: -7 });
      break;
    case 'MILD_PERIO':
      baseRate -= 3;
      factors.push({ factor: 'Mild periodontal disease', impact: -3 });
      break;
    case 'GINGIVITIS':
      baseRate -= 1;
      factors.push({ factor: 'Gingivitis', impact: -1 });
      break;
    case 'HEALTHY':
      factors.push({ factor: 'Healthy periodontium', impact: 0 });
      break;
  }

  // Bone quality impact for implant treatments
  if (treatmentType === 'IMPLANT' || treatmentType === 'ALL_ON_X' || treatmentType === 'FULL_MOUTH_REHAB') {
    switch (assessment.boneQuality) {
      case 'D1':
        baseRate += 2;
        factors.push({ factor: 'Excellent bone quality (D1)', impact: 2 });
        break;
      case 'D2':
        factors.push({ factor: 'Good bone quality (D2)', impact: 0 });
        break;
      case 'D3':
        baseRate -= 3;
        factors.push({ factor: 'Fair bone quality (D3)', impact: -3 });
        break;
      case 'D4':
        baseRate -= 8;
        factors.push({ factor: 'Poor bone quality (D4)', impact: -8 });
        break;
      case undefined:
        // Bone quality not assessed
        break;
    }
  }

  // Complexity adjustment
  if (assessment.sinusProximity) {
    baseRate -= 2;
    factors.push({ factor: 'Sinus proximity', impact: -2 });
  }

  if (assessment.nerveProximity) {
    baseRate -= 3;
    factors.push({ factor: 'Nerve proximity', impact: -3 });
  }

  // Medical conditions impact
  const highRiskConditions = ['osteoporosis', 'bisphosphonates', 'immunosuppression', 'radiation'];
  const hasHighRiskCondition = assessment.medicalConditions.some((c) =>
    highRiskConditions.some((hrc) => c.toLowerCase().includes(hrc))
  );

  if (hasHighRiskCondition) {
    baseRate -= 10;
    factors.push({ factor: 'High-risk medical condition', impact: -10 });
  }

  return {
    rate: Math.max(50, Math.min(99, baseRate)),
    factors,
  };
}

/**
 * Estimates treatment cost based on procedures and region
 */
export function estimateTreatmentCost(
  procedures: readonly ProcedureRecommendation[],
  currency = 'RON'
): { min: number; max: number; breakdown: readonly { procedure: string; cost: number }[] } {
  // Romanian dental pricing (in RON) - competitive for dental tourism
  const procedureCosts: Record<string, { min: number; max: number }> = {
    // Implants
    IMPLANT_PLACEMENT: { min: 2500, max: 4500 },
    IMPLANT_ABUTMENT: { min: 800, max: 1500 },
    IMPLANT_CROWN: { min: 1500, max: 3000 },
    ALL_ON_4_ARCH: { min: 25000, max: 40000 },
    ALL_ON_6_ARCH: { min: 35000, max: 55000 },

    // Prosthetics
    CROWN_ZIRCONIA: { min: 1500, max: 2500 },
    CROWN_EMAX: { min: 1200, max: 2000 },
    CROWN_PFM: { min: 800, max: 1500 },
    BRIDGE_UNIT: { min: 1200, max: 2000 },
    VENEER: { min: 1000, max: 1800 },
    DENTURE_COMPLETE: { min: 2000, max: 4000 },

    // Surgical
    EXTRACTION_SIMPLE: { min: 150, max: 300 },
    EXTRACTION_SURGICAL: { min: 400, max: 800 },
    BONE_GRAFT_SMALL: { min: 800, max: 1500 },
    BONE_GRAFT_LARGE: { min: 2000, max: 4000 },
    SINUS_LIFT: { min: 3000, max: 5000 },

    // General
    CONSULTATION: { min: 100, max: 200 },
    CBCT_SCAN: { min: 300, max: 500 },
    CLEANING: { min: 200, max: 400 },
    FILLING: { min: 200, max: 500 },
    ROOT_CANAL: { min: 800, max: 1500 },
  };

  const breakdown: { procedure: string; cost: number }[] = [];
  let minTotal = 0;
  let maxTotal = 0;

  for (const proc of procedures) {
    const costs = procedureCosts[proc.code] ?? { min: proc.estimatedCost * 0.8, max: proc.estimatedCost * 1.2 };
    minTotal += costs.min;
    maxTotal += costs.max;
    breakdown.push({ procedure: proc.name, cost: (costs.min + costs.max) / 2 });
  }

  // Apply currency conversion if needed (simplified)
  const conversionRates: Record<string, number> = {
    RON: 1,
    EUR: 0.2, // 1 RON ≈ 0.2 EUR
    USD: 0.22,
    GBP: 0.17,
  };

  const rate = conversionRates[currency] ?? 1;

  return {
    min: Math.round(minTotal * rate),
    max: Math.round(maxTotal * rate),
    breakdown,
  };
}

/**
 * Generates urgency assessment based on clinical findings
 */
export function assessUrgency(assessment: ClinicalAssessmentInput): {
  level: 'ROUTINE' | 'SOON' | 'URGENT' | 'EMERGENCY';
  reasoning: string;
  recommendedTimeframe: string;
} {
  // Check for emergency conditions
  const emergencyConditions = assessment.medicalConditions.some((c) =>
    ['abscess', 'acute pain', 'swelling', 'infection', 'trauma'].some((ec) =>
      c.toLowerCase().includes(ec)
    )
  );

  if (emergencyConditions) {
    return {
      level: 'EMERGENCY',
      reasoning: 'Acute condition requiring immediate attention',
      recommendedTimeframe: 'Within 24-48 hours',
    };
  }

  // Check for urgent conditions
  if (assessment.periodontalStatus === 'SEVERE_PERIO') {
    return {
      level: 'URGENT',
      reasoning: 'Severe periodontal disease requires prompt treatment to prevent tooth loss',
      recommendedTimeframe: 'Within 1-2 weeks',
    };
  }

  if (assessment.existingRestorations.some((r) => r.condition === 'FAILING')) {
    return {
      level: 'URGENT',
      reasoning: 'Failing restorations need replacement before complications arise',
      recommendedTimeframe: 'Within 2-4 weeks',
    };
  }

  // Check for soon conditions
  if (assessment.decayedTeeth.length > 3) {
    return {
      level: 'SOON',
      reasoning: 'Multiple decayed teeth should be treated before progression',
      recommendedTimeframe: 'Within 1-2 months',
    };
  }

  if (assessment.missingTeeth.length > 0 && assessment.missingTeeth.length < 6) {
    return {
      level: 'SOON',
      reasoning: 'Missing teeth affecting function - replacement recommended soon',
      recommendedTimeframe: 'Within 2-3 months',
    };
  }

  return {
    level: 'ROUTINE',
    reasoning: 'No urgent concerns - proceed with standard treatment planning timeline',
    recommendedTimeframe: 'At patient convenience (within 6 months)',
  };
}

/**
 * Creates a patient-friendly summary of the treatment plan
 */
export function createPatientFriendlySummary(
  option: TreatmentOption,
  language: 'ro' | 'en' | 'de' = 'en'
): string {
  const summaries: Record<'ro' | 'en' | 'de', (opt: TreatmentOption) => string> = {
    en: (opt) => `
Your Recommended Treatment: ${opt.name}

What we'll do: ${opt.description}

This treatment has a ${opt.predictedSuccessRate}% success rate based on your specific situation.

Timeline: Approximately ${opt.estimatedDurationMonths} months with ${opt.appointmentsRequired} appointments.

Investment: ${opt.estimatedCost.min.toLocaleString()}-${opt.estimatedCost.max.toLocaleString()} ${opt.estimatedCost.currency}

What to expect:
${opt.phases.map((p, i) => `${i + 1}. ${p.name}: ${p.description}`).join('\n')}

Our team will guide you through each step, ensuring your comfort and answering all questions.
    `.trim(),

    ro: (opt) => `
Tratamentul Recomandat: ${opt.name}

Ce vom face: ${opt.description}

Acest tratament are o rată de succes de ${opt.predictedSuccessRate}% bazată pe situația dumneavoastră specifică.

Durată: Aproximativ ${opt.estimatedDurationMonths} luni cu ${opt.appointmentsRequired} programări.

Investiție: ${opt.estimatedCost.min.toLocaleString()}-${opt.estimatedCost.max.toLocaleString()} ${opt.estimatedCost.currency}

La ce să vă așteptați:
${opt.phases.map((p, i) => `${i + 1}. ${p.name}: ${p.description}`).join('\n')}

Echipa noastră vă va ghida în fiecare etapă, asigurându-vă confortul și răspunzând la toate întrebările.
    `.trim(),

    de: (opt) => `
Empfohlene Behandlung: ${opt.name}

Was wir tun werden: ${opt.description}

Diese Behandlung hat eine Erfolgsrate von ${opt.predictedSuccessRate}% basierend auf Ihrer spezifischen Situation.

Zeitrahmen: Ungefähr ${opt.estimatedDurationMonths} Monate mit ${opt.appointmentsRequired} Terminen.

Investition: ${opt.estimatedCost.min.toLocaleString()}-${opt.estimatedCost.max.toLocaleString()} ${opt.estimatedCost.currency}

Was Sie erwarten können:
${opt.phases.map((p, i) => `${i + 1}. ${p.name}: ${p.description}`).join('\n')}

Unser Team wird Sie durch jeden Schritt begleiten und für Ihren Komfort sorgen.
    `.trim(),
  };

  return summaries[language](option);
}

/**
 * Validates that a treatment plan is clinically sound
 */
export function validateTreatmentPlan(plan: AITreatmentPlan): {
  isValid: boolean;
  errors: readonly string[];
  warnings: readonly string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check success rate is realistic
  if (plan.recommendedOption.predictedSuccessRate > 99) {
    warnings.push('Success rate seems optimistic - verify clinical basis');
  }

  if (plan.recommendedOption.predictedSuccessRate < 60) {
    warnings.push('Low predicted success rate - consider alternative approaches');
  }

  // Check cost estimates are provided
  if (plan.recommendedOption.estimatedCost.min <= 0) {
    errors.push('Invalid cost estimate');
  }

  // Check phases are logically ordered
  const hasHealingGaps = plan.recommendedOption.phases.some(
    (p) => p.requiresHealing && !p.healingWeeks
  );
  if (hasHealingGaps) {
    errors.push('Healing time not specified for phases requiring healing');
  }

  // Check contraindications
  if (plan.recommendedOption.contraindications.length > 0) {
    warnings.push(`${plan.recommendedOption.contraindications.length} contraindication(s) identified - ensure patient eligibility`);
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}
