// WhatsApp schemas
export {
  WhatsAppContactSchema,
  WhatsAppTextSchema,
  WhatsAppMessageSchema,
  WhatsAppStatusSchema,
  WhatsAppMetadataSchema,
  WhatsAppValueSchema,
  WhatsAppChangeSchema,
  WhatsAppEntrySchema,
  WhatsAppWebhookSchema,
  type WhatsAppContact,
  type WhatsAppText,
  type WhatsAppMessage,
  type WhatsAppStatus,
  type WhatsAppMetadata,
  type WhatsAppValue,
  type WhatsAppChange,
  type WhatsAppEntry,
  type WhatsAppWebhook,
} from './whatsapp.schema.js';

// Voice schemas
export {
  CallDirectionSchema,
  CallStatusSchema,
  TwilioBaseSchema,
  VoiceWebhookSchema,
  CallStatusCallbackSchema,
  VoiceEventSchema,
  type CallDirection,
  type CallStatus,
  type VoiceWebhook,
  type CallStatusCallback,
  type VoiceEvent,
} from './voice.schema.js';

// Lead and scoring schemas
export {
  LeadChannelSchema,
  LeadScoreSchema,
  UTMParamsSchema,
  LeadContextSchema,
  ScoringOutputSchema,
  type LeadChannel,
  type LeadScore,
  type UTMParams,
  type LeadContext,
  type ScoringOutput,
} from './lead.schema.js';

// Stripe schemas
export {
  StripeEventTypeSchema,
  PaymentIntentSchema,
  ChargeSchema,
  StripeCustomerSchema,
  InvoiceSchema,
  CheckoutSessionSchema,
  StripeWebhookEventSchema,
  PaymentEventSchema,
  type StripeEventType,
  type PaymentIntent,
  type Charge,
  type StripeCustomer,
  type Invoice,
  type CheckoutSession,
  type StripeWebhookEvent,
  type PaymentEvent,
} from './stripe.schema.js';

// HubSpot schemas
export {
  HubSpotContactPropertiesSchema,
  HubSpotContactSchema,
  HubSpotContactInputSchema,
  HubSpotFilterSchema,
  HubSpotFilterGroupSchema,
  HubSpotSearchRequestSchema,
  HubSpotSearchResponseSchema,
  HubSpotTimelineEventSchema,
  HubSpotTaskSchema,
  type HubSpotContactProperties,
  type HubSpotContact,
  type HubSpotContactInput,
  type HubSpotFilter,
  type HubSpotFilterGroup,
  type HubSpotSearchRequest,
  type HubSpotSearchResponse,
  type HubSpotTimelineEvent,
  type HubSpotTask,
} from './hubspot.schema.js';

// Patient/Lead schemas for Dashboard
export {
  PatientStatusSchema,
  LeadClassificationSchema,
  LeadSourceSchema,
  PatientListItemSchema,
  RecentLeadSchema,
  DashboardStatsSchema,
  type PatientStatus,
  type LeadClassification,
  type LeadSource,
  type PatientListItem,
  type RecentLead,
  type DashboardStats,
} from './patient.schema.js';

// Dashboard & UI schemas
export {
  // Triage
  TriageColumnIdSchema,
  TriageLeadSchema,
  TriageColumnSchema,
  // Calendar
  AppointmentStatusSchema,
  TimeSlotSchema,
  DayScheduleSchema,
  // Analytics
  AnalyticsMetricsSchema,
  TimeSeriesDataPointSchema,
  LeadsBySourceSchema,
  ConversionFunnelStepSchema,
  TopProcedureSchema,
  OperatorPerformanceSchema,
  // Messages
  MessageDirectionSchema,
  MessageStatusSchema,
  ConversationStatusSchema,
  ConversationChannelSchema,
  MessageSchema,
  ConversationSchema,
  // Patient Detail
  PatientActivityTypeSchema,
  PatientActivitySchema,
  PatientAppointmentSchema,
  PatientDocumentSchema,
  PatientNoteSchema,
  PatientDetailSchema,
  // Types
  type TriageColumnId,
  type TriageLead,
  type TriageColumn,
  type AppointmentStatus,
  type TimeSlot,
  type DaySchedule,
  type AnalyticsMetrics,
  type TimeSeriesDataPoint,
  type LeadsBySource,
  type ConversionFunnelStep,
  type TopProcedure,
  type OperatorPerformance,
  type MessageDirection,
  type MessageStatus,
  type ConversationStatus,
  type ConversationChannel,
  type Message,
  type Conversation,
  type PatientActivityType,
  type PatientActivity,
  type PatientAppointment,
  type PatientDocument,
  type PatientNote,
  type PatientDetail,
} from './dashboard.schema.js';

// Domain events schemas
export {
  EventBaseSchema,
  WhatsAppMessageReceivedEventSchema,
  WhatsAppMessageSentEventSchema,
  WhatsAppStatusUpdateEventSchema,
  VoiceCallInitiatedEventSchema,
  VoiceCallCompletedEventSchema,
  VoiceTranscriptReadyEventSchema,
  LeadCreatedEventSchema,
  LeadScoredEventSchema,
  LeadQualifiedEventSchema,
  LeadAssignedEventSchema,
  PaymentReceivedEventSchema,
  PaymentFailedEventSchema,
  AppointmentScheduledEventSchema,
  AppointmentReminderSentEventSchema,
  ConsentRecordedEventSchema,
  DomainEventSchema,
  type EventBase,
  type WhatsAppMessageReceivedEvent,
  type WhatsAppMessageSentEvent,
  type WhatsAppStatusUpdateEvent,
  type VoiceCallInitiatedEvent,
  type VoiceCallCompletedEvent,
  type VoiceTranscriptReadyEvent,
  type LeadCreatedEvent,
  type LeadScoredEvent,
  type LeadQualifiedEvent,
  type LeadAssignedEvent,
  type PaymentReceivedEvent,
  type PaymentFailedEvent,
  type AppointmentScheduledEvent,
  type AppointmentReminderSentEvent,
  type ConsentRecordedEvent,
  type DomainEvent,
} from './events.schema.js';
