#!/usr/bin/env node
/**
 * XRAY Audit CLI
 * 
 * Command-line interface for running comprehensive architecture audits.
 * 
 * Usage:
 *   pnpm xray-audit                    # Audit current directory
 *   pnpm xray-audit --output report.md # Save to file
 *   pnpm xray-audit --verbose          # Verbose output
 */

import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { AuditEngine, ReportGenerator } from './xray-audit/index.js';

interface CLIOptions {
  rootPath: string;
  output?: string;
  verbose: boolean;
  medicalGrade: boolean;
}

function parseArgs(): CLIOptions {
  const args = process.argv.slice(2);
  
  const options: CLIOptions = {
    rootPath: process.cwd(),
    verbose: false,
    medicalGrade: true,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    switch (arg) {
      case '--output':
      case '-o':
        options.output = args[++i];
        break;
      case '--verbose':
      case '-v':
        options.verbose = true;
        break;
      case '--path':
      case '-p':
        options.rootPath = resolve(args[++i]);
        break;
      case '--no-medical-grade':
        options.medicalGrade = false;
        break;
      case '--help':
      case '-h':
        printHelp();
        process.exit(0);
        break;
      default:
        if (!arg.startsWith('-')) {
          options.rootPath = resolve(arg);
        }
    }
  }

  return options;
}

function printHelp(): void {
  console.log(`
XRAY Audit CLI - MedicalCor Architecture Standard

Usage:
  pnpm xray-audit [options] [path]

Options:
  -o, --output <file>      Save report to file (default: stdout)
  -v, --verbose            Enable verbose output
  -p, --path <directory>   Repository path to audit (default: current directory)
  --no-medical-grade       Disable medical-grade compliance checks
  -h, --help               Show this help message

Examples:
  pnpm xray-audit
  pnpm xray-audit --output XRAY_AUDIT_REPORT.md
  pnpm xray-audit --verbose --path /path/to/repo
  pnpm xray-audit . --output report.md

Description:
  Performs comprehensive architecture audit against MedicalCor standards:
  - DDD & Hexagonal Architecture validation
  - Security & Privacy analysis (Zero-Trust, PII, RLS)
  - Event-Driven patterns (CQRS, Outbox, Idempotency)
  - Observability (Logging, Metrics, Tracing)
  - AI-Readiness & Data Quality
  - Testing & CI/CD coverage

Generated by: GITHUB_REPO_XRAY_AGENT_MC
  `);
}

async function main() {
  const options = parseArgs();

  console.log('╔═══════════════════════════════════════════════════════════╗');
  console.log('║   XRAY AUDIT - MedicalCor Architecture Standard          ║');
  console.log('║   State-of-the-Art Repository Analysis                   ║');
  console.log('╚═══════════════════════════════════════════════════════════╝\n');

  console.log(`📂 Repository: ${options.rootPath}`);
  console.log(`🏥 Medical-Grade: ${options.medicalGrade ? 'YES' : 'NO'}`);
  console.log(`📊 Verbose: ${options.verbose ? 'YES' : 'NO'}\n`);

  try {
    // Initialize audit engine
    const engine = new AuditEngine(options.rootPath, {
      verbose: options.verbose,
      medicalGrade: options.medicalGrade,
      excludePaths: ['node_modules', '.git', 'dist', 'build', '.next'],
    });

    // Run full audit
    console.log('⏳ Running comprehensive audit...\n');
    const startTime = Date.now();
    
    const report = await engine.runFullAudit();
    
    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`✅ Audit completed in ${duration}s\n`);

    // Generate report
    console.log('📝 Generating report...\n');
    const generator = new ReportGenerator();
    const markdown = generator.generateMarkdownReport(report);

    // Output results
    if (options.output) {
      await writeFile(options.output, markdown, 'utf-8');
      console.log(`📄 Report saved to: ${options.output}`);
    } else {
      console.log('\n' + '='.repeat(80) + '\n');
      console.log(markdown);
      console.log('\n' + '='.repeat(80) + '\n');
    }

    // Print summary
    console.log('\n╔═══════════════════════════════════════════════════════════╗');
    console.log('║                     AUDIT SUMMARY                         ║');
    console.log('╚═══════════════════════════════════════════════════════════╝\n');
    console.log(`Overall Score:        ${report.overallScore.toFixed(1)}/10.0`);
    console.log(`Total Issues:         ${report.issues.length}`);
    console.log(`  - HIGH Priority:    ${report.recommendations.phase0.length}`);
    console.log(`  - MEDIUM Priority:  ${report.recommendations.phase1.length + report.recommendations.phase2.length}`);
    console.log(`  - LOW Priority:     ${report.recommendations.phase3.length}`);
    console.log(`\nFiles Analyzed:       ${report.structure.totalFiles.toLocaleString()}`);
    console.log(`Lines of Code:        ${report.structure.totalLines.toLocaleString()}`);
    console.log(`\nNext Steps:`);
    console.log(`  1. Review Phase 0 (HIGH priority) issues`);
    console.log(`  2. Create GitHub issues for critical items`);
    console.log(`  3. Assign owners and deadlines`);
    console.log(`  4. Schedule follow-up audit\n`);

    // Exit with appropriate code
    const criticalIssues = report.recommendations.phase0.length;
    if (criticalIssues > 0) {
      console.log(`⚠️  ${criticalIssues} critical issues require immediate attention\n`);
      process.exit(1);
    } else {
      console.log('✅ No critical issues detected\n');
      process.exit(0);
    }
  } catch (error) {
    console.error('\n❌ Audit failed:');
    console.error(error);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { main };
